#%RAML 1.0 Trait
headers:
  client_id:
    type: string
    required: true
    description: Llave del cliente
    displayName: Llave del cliente
  client_secret:
    type: string
    required: true
    description: Llave secreta del cliente
    displayName: Llave secreta del cliente