#%RAML 1.0 Trait
responses:
  401:
    body:
      application/json:
        description: NOT AUTHORIZED
        displayName: NOT AUTHORIZED
        example: {
          message : "NOT AUTHORIZED"
        }